### ISSUE TITLE
Inventory management

### ISSUE THREAD

**Issue by T4g1** [T4g1/gd-wildjam18#10]
Player will be able to gather few items during the game. We need a way to show that quickly.

There will not be a lot of them (like 10 is a lot) so a quick a small UI to show that is enough.

I'm not even sure we need to preserve inventory between levels.

**Comment by tienlocnguyen** [comment]
We just need a button to show inventory and implement an array to manage it, right?

**Comment by T4g1** [comment]
We'll see about the UI later on. We only need something to store/interact with a player inventory
