### ISSUE TITLE
First level

### ISSUE THREAD

**Issue by T4g1** [T4g1/gd-wildjam18#5]
Design first level roughly so we can start implementing it

**Comment by tienlocnguyen** [comment]
I implemented simple running scene at: https://github.com/T4g1/gd-wildjam18/pull/12

**Comment by T4g1** [comment]
We need to design a first level concording with https://docs.google.com/document/d/1WScGc7RAKU3ya5U47Ysd48-caNm3wChnynDQNc-YV9E/edit?usp=sharing
